create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    login varchar(40) not null unique,
    name varchar(40),
    birthday date not null,
    constraint login_no_spaces check (regexp_like(login, '^\S+$')),
    constraint birthday_not_future check (birthday <= current_date)
);

create table if not exists friendship (
    user_id bigint not null references users(id) on delete cascade,
    friend_id bigint not null references users(id) on delete cascade,
    status varchar(12) not null,
    created_at timestamp with time zone default current_timestamp,
    constraint default_status_check check (status in ('UNCONFIRMED', 'CONFIRMED')),
    constraint friendship_pk primary key (user_id, friend_id),
    constraint no_self_friend check (user_id <> friend_id)
);

create table if not exists mpa_ratings (
    id bigint generated by default as identity primary key,
    name varchar(40) unique not null
);

create table if not exists films (
    id bigint generated by default as identity primary key,
    name varchar(40) not null,
    description varchar(255),
    release_date date not null,
    duration integer not null,
    mpa_rating_id bigint not null references mpa_ratings(id),
    constraint release_date_not_future check (release_date <= current_date),
    constraint duration_not_negative check (duration > 0)
);

create table if not exists genres (
    id bigint generated by default as identity primary key,
    name varchar(40) unique not null
);

create table if not exists film_genres (
    film_id bigint not null references films(id) on delete cascade,
    genre_id bigint not null references genres(id) on delete cascade,
    constraint film_genres_pk primary key (film_id, genre_id)
);

create table if not exists film_likes (
    user_id bigint not null references users(id) on delete cascade,
    film_id bigint not null references films(id) on delete cascade,
    created_at timestamp with time zone default current_timestamp,
    constraint like_pk primary key (user_id, film_id)
);
